# Generated by Django 4.2 on 2023-04-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название резюме')),
                ('category', models.TextField(blank=True, choices=[('IT', 'IT'), ('DESIGN', 'Дизайн'), ('MANAGEMENT', 'Менеджмент'), ('MEDICINE', 'Медицина'), ('ENGINEERING', 'Инженерное дело'), ('ART', 'Искусство'), ('TRANSPORT', 'Транспорт'), ('MARKETING', 'Маркетинг'), ('TRADE', 'Торговля'), ('ECONOMY', 'Экономика')], null=True, verbose_name='Категория вакансии')),
                ('about', models.TextField(max_length=3000, verbose_name='О себе')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Желаемая зарплата')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Последние изменение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Скрыть резюме')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на телеграм')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Linkedin')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Facebook')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
        ),
    ]
